USE master
go
CREATE DATABASE Demo 
ON PRIMARY
(
    NAME='Demo',
    FILENAME='C:\workspace-git\CrystalReports-ParentChild\Demo.mdf',
    SIZE=4096KB,
    MAXSIZE=UNLIMITED,
    FILEGROWTH=1024KB
)
LOG ON
(
    NAME='Demo_log',
    FILENAME='C:\workspace-git\CrystalReports-ParentChild\Demo_log.ldf',
    SIZE=1024KB,
    MAXSIZE=UNLIMITED,
    FILEGROWTH=10%
)
COLLATE SQL_Latin1_General_CP1_CI_AS
go
EXEC sp_dbcmptlevel N'Demo',110
go
USE Demo
go
EXEC sp_changedbowner N'sa'
go
USE master
go
ALTER DATABASE Demo SET ANSI_NULL_DEFAULT OFF
go
ALTER DATABASE Demo SET ANSI_NULLS OFF
go
ALTER DATABASE Demo SET ANSI_PADDING OFF
go
ALTER DATABASE Demo SET ANSI_WARNINGS OFF
go
ALTER DATABASE Demo SET ARITHABORT OFF
go
ALTER DATABASE Demo SET AUTO_CREATE_STATISTICS ON
go
ALTER DATABASE Demo SET AUTO_UPDATE_STATISTICS ON
go
ALTER DATABASE Demo SET AUTO_CLOSE OFF
go
ALTER DATABASE Demo SET AUTO_SHRINK OFF
go
ALTER DATABASE Demo SET CONCAT_NULL_YIELDS_NULL OFF
go
ALTER DATABASE Demo SET CURSOR_CLOSE_ON_COMMIT OFF
go
EXEC sp_replicationdboption N'Demo','merge publish',false
go
ALTER DATABASE Demo SET NUMERIC_ROUNDABORT OFF
go
EXEC sp_replicationdboption N'Demo','publish',false
go
ALTER DATABASE Demo SET QUOTED_IDENTIFIER OFF
go
ALTER DATABASE Demo SET RECURSIVE_TRIGGERS OFF
go
EXEC sp_replicationdboption N'Demo','subscribe',false
go
ALTER DATABASE Demo SET TORN_PAGE_DETECTION ON
go
ALTER DATABASE Demo SET DISABLE_BROKER
go
ALTER DATABASE Demo SET DATE_CORRELATION_OPTIMIZATION OFF
go
ALTER DATABASE Demo SET ALLOW_SNAPSHOT_ISOLATION OFF
go
ALTER DATABASE Demo SET READ_COMMITTED_SNAPSHOT OFF
go
ALTER DATABASE Demo SET PARAMETERIZATION SIMPLE
go
ALTER DATABASE Demo SET PAGE_VERIFY TORN_PAGE_DETECTION
go
ALTER DATABASE Demo SET RECOVERY SIMPLE
go
ALTER DATABASE Demo SET CURSOR_DEFAULT GLOBAL
go
ALTER DATABASE Demo SET READ_WRITE
go
ALTER DATABASE Demo SET MULTI_USER
go
IF DB_ID(N'Demo') IS NOT NULL
    PRINT N'<<< CREATED DATABASE Demo >>>'
ELSE
    PRINT N'<<< FAILED CREATING DATABASE Demo >>>'
go
